# Generated by Django 3.0.8 on 2020-07-31 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0002_album_album_cover'),
    ]

    operations = [
        migrations.CreateModel(
            name='Genre',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('genre', models.CharField(choices=[('Rock', 'Rock'), ('HipHop', 'HipHop'), ('Electronic', 'Electronic')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='album',
            name='genre',
            field=models.ManyToManyField(to='music_store.Genre'),
        ),
    ]
