# Generated by Django 3.0.8 on 2020-08-06 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0006_auto_20200806_1342'),
    ]

    operations = [
        migrations.AddField(
            model_name='album',
            name='number_of_ratings',
            field=models.IntegerField(default=0),
        ),
    ]
