# Generated by Django 3.0.8 on 2021-05-01 22:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0011_auto_20210501_2222'),
    ]

    operations = [
        migrations.AddField(
            model_name='artist',
            name='biography',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='song',
            name='duration',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='feature_artists',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='music_store.Artist'),
        ),
    ]
