# Generated by Django 3.0.8 on 2021-05-01 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0012_auto_20210501_2243'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='song',
            name='feature_artists',
        ),
        migrations.AddField(
            model_name='song',
            name='feature_artists',
            field=models.ManyToManyField(null=True, to='music_store.Artist'),
        ),
    ]
