# Generated by Django 3.0.8 on 2021-05-01 23:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0014_auto_20210501_2309'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='album',
            name='avaliable',
        ),
        migrations.RemoveField(
            model_name='album',
            name='average_rating',
        ),
        migrations.RemoveField(
            model_name='album',
            name='in_stock',
        ),
        migrations.RemoveField(
            model_name='album',
            name='number_of_ratings',
        ),
    ]
