# Generated by Django 3.0.8 on 2021-05-08 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0018_auto_20210501_2351'),
    ]

    operations = [
        migrations.CreateModel(
            name='NotableInstrument',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instrument', models.CharField(choices=[('Accordion', 'Fast'), ('Acoustic Guitar', 'Acoustic Guitar'), ('Acoustic Piano', 'Acoustic Piano'), ('Banjo', 'Banjo'), ('Bass', 'Bass'), ('Choir', ' Choir'), ('Clarinet', ' Clarinet'), ('Electric Guitar', ' Electric Guitar'), ('Electric Piano', ' Electric Piano'), ('Flute', ' Flute'), ('Saxophone', ' Saxophone'), ('Synthesiser', ' Synthesiser'), ('Violin', ' Violin'), ('Drums', ' Drums')], max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='TrackTempo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tempo', models.CharField(choices=[('Fast', 'Fast'), ('Moderate', 'Moderate'), ('Multiple', 'Multiple'), ('Slow', 'Slow'), ('Very Fast', 'Very Fast'), ('Very Slow', ' Very Slow')], max_length=50, null=True)),
            ],
        ),
        migrations.AddField(
            model_name='song',
            name='audio_file',
            field=models.FileField(blank=True, null=True, upload_to='static/files'),
        ),
        migrations.AddField(
            model_name='song',
            name='notable_instruments',
            field=models.ManyToManyField(to='music_store.NotableInstrument'),
        ),
        migrations.AddField(
            model_name='song',
            name='track_tempo',
            field=models.ManyToManyField(to='music_store.TrackTempo'),
        ),
    ]
