# Generated by Django 3.0.8 on 2021-06-08 19:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0024_auto_20210606_1344'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='decade',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
