# Generated by Django 3.0.8 on 2021-06-22 17:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0025_song_decade'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='bitrate',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='song',
            name='duration',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
