# Generated by Django 3.0.8 on 2021-06-27 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('music_store', '0027_auto_20210622_2027'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TrackTempo',
        ),
    ]
